// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlgen

import (
	"time"
)

type Node struct {
	ID      int64
	Uuid    string
	Name    string
	BaseUri string
}

type User struct {
	ID                  int64
	Uuid                string
	Description         string
	Scopes              string
	Fee                 string
	PaidUntil           *time.Time
	IsBanned            bool
	LoginTokenVersion   int64
	RefreshTokenVersion int64
}
