// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlgen

import (
	"context"
)

const addNode = `-- name: AddNode :one
INSERT INTO nodes (
    uuid,
    name,
    base_uri
) VALUES (
    ?1,
    ?2,
    ?3
) RETURNING id, uuid, name, base_uri
`

type AddNodeParams struct {
	Uuid    string
	Name    string
	BaseUri string
}

func (q *Queries) AddNode(ctx context.Context, arg AddNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, addNode, arg.Uuid, arg.Name, arg.BaseUri)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUri,
	)
	return i, err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
SELECT id, uuid, name, base_uri FROM nodes
WHERE uuid = ?1
`

func (q *Queries) GetNodeByUUID(ctx context.Context, uuid string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, uuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUri,
	)
	return i, err
}

const getNodes = `-- name: GetNodes :many
SELECT id, uuid, name, base_uri FROM nodes
`

func (q *Queries) GetNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, getNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.BaseUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeNode = `-- name: RemoveNode :execrows
DELETE FROM nodes WHERE id = ?1
`

func (q *Queries) RemoveNode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET
    name = ?1,
    base_uri = ?2
WHERE uuid = ?3
RETURNING id, uuid, name, base_uri
`

type UpdateNodeParams struct {
	Name    string
	BaseUri string
	Uuid    string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode, arg.Name, arg.BaseUri, arg.Uuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUri,
	)
	return i, err
}
