// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlgen

import (
	"context"
	"time"
)

const addNode = `-- name: AddNode :one
INSERT INTO nodes (
    uuid,
    name,
    base_uri
) VALUES (
    ?1,
    ?2,
    ?3
) RETURNING id, uuid, name, base_uri
`

type AddNodeParams struct {
	Uuid    string
	Name    string
	BaseUri string
}

func (q *Queries) AddNode(ctx context.Context, arg AddNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, addNode, arg.Uuid, arg.Name, arg.BaseUri)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUri,
	)
	return i, err
}

const addUser = `-- name: AddUser :one
INSERT INTO users (
    uuid,
    description,
    scopes,
    fee,
    is_banned
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    FALSE
) RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type AddUserParams struct {
	Uuid        string
	Description string
	Scopes      string
	Fee         string
}

func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Uuid,
		arg.Description,
		arg.Scopes,
		arg.Fee,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const banUser = `-- name: BanUser :one
UPDATE users SET
    is_banned = ?1
WHERE uuid = ?2
RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type BanUserParams struct {
	Banned bool
	Uuid   string
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, banUser, arg.Banned, arg.Uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
SELECT id, uuid, name, base_uri FROM nodes
WHERE uuid = ?1
`

func (q *Queries) GetNodeByUUID(ctx context.Context, uuid string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, uuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUri,
	)
	return i, err
}

const getNodes = `-- name: GetNodes :many
SELECT id, uuid, name, base_uri FROM nodes
`

func (q *Queries) GetNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, getNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.BaseUri,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUser = `-- name: GetUser :one
SELECT id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version FROM users
WHERE uuid = ?1
`

func (q *Queries) GetUser(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const getUserAndUpdateForLogin = `-- name: GetUserAndUpdateForLogin :one
UPDATE users SET
    login_token_version = login_token_version +1
WHERE
    uuid = ?1
    AND login_token_version = ?2
RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type GetUserAndUpdateForLoginParams struct {
	Uuid                string
	CurrentLoginVersion int64
}

func (q *Queries) GetUserAndUpdateForLogin(ctx context.Context, arg GetUserAndUpdateForLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserAndUpdateForLogin, arg.Uuid, arg.CurrentLoginVersion)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Description,
			&i.Scopes,
			&i.Fee,
			&i.PaidUntil,
			&i.IsBanned,
			&i.LoginTokenVersion,
			&i.RefreshTokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserLoginVersion = `-- name: IncrementUserLoginVersion :one
UPDATE users SET
    login_token_version = login_token_version + 1
WHERE
    uuid = ?1
RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

func (q *Queries) IncrementUserLoginVersion(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, incrementUserLoginVersion, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const incrementUserRefreshVersion = `-- name: IncrementUserRefreshVersion :one
UPDATE users SET
    refresh_token_version = refresh_token_version + 1
WHERE
    uuid = ?1
RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

func (q *Queries) IncrementUserRefreshVersion(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, incrementUserRefreshVersion, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const removeNode = `-- name: RemoveNode :execrows
DELETE FROM nodes WHERE id = ?1
`

func (q *Queries) RemoveNode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET
    name = ?1,
    base_uri = ?2
WHERE uuid = ?3
RETURNING id, uuid, name, base_uri
`

type UpdateNodeParams struct {
	Name    string
	BaseUri string
	Uuid    string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode, arg.Name, arg.BaseUri, arg.Uuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUri,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    description = ?1,
    scopes = ?2,
    fee = ?3
WHERE uuid = ?4
RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type UpdateUserParams struct {
	Description string
	Scopes      string
	Fee         string
	Uuid        string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Description,
		arg.Scopes,
		arg.Fee,
		arg.Uuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const updateUserPaidUntil = `-- name: UpdateUserPaidUntil :one
UPDATE users SET
    paid_until = ?1
WHERE uuid = ?2
RETURNING id, uuid, description, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type UpdateUserPaidUntilParams struct {
	PaidUntil *time.Time
	Uuid      string
}

func (q *Queries) UpdateUserPaidUntil(ctx context.Context, arg UpdateUserPaidUntilParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPaidUntil, arg.PaidUntil, arg.Uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Description,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}
