// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package sqlgen

import (
	"context"
	"time"
)

const addNode = `-- name: AddNode :one

INSERT INTO nodes (
    uuid,
    name,
    base_url,
    tls_client_key,
    tls_client_cert,
    tls_server_cert,
    allowed_ips
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6,
    ?7
) RETURNING id, uuid, name, base_url, tls_client_key, tls_client_cert, tls_server_cert, allowed_ips
`

type AddNodeParams struct {
	Uuid          string
	Name          string
	BaseUrl       string
	TlsClientKey  string
	TlsClientCert string
	TlsServerCert string
	AllowedIps    string
}

// - ======= Nodes =======
func (q *Queries) AddNode(ctx context.Context, arg AddNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, addNode,
		arg.Uuid,
		arg.Name,
		arg.BaseUrl,
		arg.TlsClientKey,
		arg.TlsClientCert,
		arg.TlsServerCert,
		arg.AllowedIps,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUrl,
		&i.TlsClientKey,
		&i.TlsClientCert,
		&i.TlsServerCert,
		&i.AllowedIps,
	)
	return i, err
}

const addUser = `-- name: AddUser :one

INSERT INTO users (
    uuid,
    name,
    scopes,
    fee,
    is_banned
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    FALSE
) RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type AddUserParams struct {
	Uuid   string
	Name   string
	Scopes string
	Fee    string
}

// - ======= Users =======
func (q *Queries) AddUser(ctx context.Context, arg AddUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, addUser,
		arg.Uuid,
		arg.Name,
		arg.Scopes,
		arg.Fee,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const banUser = `-- name: BanUser :one
UPDATE users SET
    is_banned = ?1
WHERE uuid = ?2
RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type BanUserParams struct {
	Banned bool
	Uuid   string
}

func (q *Queries) BanUser(ctx context.Context, arg BanUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, banUser, arg.Banned, arg.Uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const cancelPeerRequest = `-- name: CancelPeerRequest :one
UPDATE peer_requests SET
    status = 'cancelled'
WHERE
    random_id = ?1
RETURNING id, random_id, interface_name, requested_at, requested_by_user_uuid, node_id, owned_by_user_id, status
`

func (q *Queries) CancelPeerRequest(ctx context.Context, randomID string) (PeerRequest, error) {
	row := q.db.QueryRowContext(ctx, cancelPeerRequest, randomID)
	var i PeerRequest
	err := row.Scan(
		&i.ID,
		&i.RandomID,
		&i.InterfaceName,
		&i.RequestedAt,
		&i.RequestedByUserUuid,
		&i.NodeID,
		&i.OwnedByUserID,
		&i.Status,
	)
	return i, err
}

const createPeerRequest = `-- name: CreatePeerRequest :exec

INSERT INTO peer_requests (
    random_id,
    interface_name,
    requested_at,
    requested_by_user_uuid,
    node_id,
    owned_by_user_id
) VALUES (
    ?1,
    ?2,
    ?3,
    ?4,
    ?5,
    ?6
)
`

type CreatePeerRequestParams struct {
	RandomID            string
	InterfaceName       string
	RequestedAt         time.Time
	RequestedByUserUuid *string
	NodeID              int64
	OwnedByUserID       int64
}

// - ======= Peer requests =======
func (q *Queries) CreatePeerRequest(ctx context.Context, arg CreatePeerRequestParams) error {
	_, err := q.db.ExecContext(ctx, createPeerRequest,
		arg.RandomID,
		arg.InterfaceName,
		arg.RequestedAt,
		arg.RequestedByUserUuid,
		arg.NodeID,
		arg.OwnedByUserID,
	)
	return err
}

const getNodeByUUID = `-- name: GetNodeByUUID :one
SELECT id, uuid, name, base_url, tls_client_key, tls_client_cert, tls_server_cert, allowed_ips FROM nodes
WHERE uuid = ?1
`

func (q *Queries) GetNodeByUUID(ctx context.Context, uuid string) (Node, error) {
	row := q.db.QueryRowContext(ctx, getNodeByUUID, uuid)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUrl,
		&i.TlsClientKey,
		&i.TlsClientCert,
		&i.TlsServerCert,
		&i.AllowedIps,
	)
	return i, err
}

const getNodes = `-- name: GetNodes :many
SELECT id, uuid, name, base_url, tls_client_key, tls_client_cert, tls_server_cert, allowed_ips FROM nodes
`

func (q *Queries) GetNodes(ctx context.Context) ([]Node, error) {
	rows, err := q.db.QueryContext(ctx, getNodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Node
	for rows.Next() {
		var i Node
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.BaseUrl,
			&i.TlsClientKey,
			&i.TlsClientCert,
			&i.TlsServerCert,
			&i.AllowedIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPeerRequestByRandomID = `-- name: GetPeerRequestByRandomID :one
SELECT peer_requests.id, peer_requests.random_id, peer_requests.interface_name, peer_requests.requested_at, peer_requests.requested_by_user_uuid, peer_requests.node_id, peer_requests.owned_by_user_id, peer_requests.status, owners.id, owners.uuid, owners.name, owners.scopes, owners.fee, owners.paid_until, owners.is_banned, owners.login_token_version, owners.refresh_token_version, nodes.id, nodes.uuid, nodes.name, nodes.base_url, nodes.tls_client_key, nodes.tls_client_cert, nodes.tls_server_cert, nodes.allowed_ips
FROM peer_requests
    JOIN nodes on nodes.id = peer_requests.node_id
    JOIN users AS owners on owners.id = peer_requests.owned_by_user_id
WHERE
    peer_requests.random_id = ?1
`

type GetPeerRequestByRandomIDRow struct {
	PeerRequest PeerRequest
	User        User
	Node        Node
}

func (q *Queries) GetPeerRequestByRandomID(ctx context.Context, randomID string) (GetPeerRequestByRandomIDRow, error) {
	row := q.db.QueryRowContext(ctx, getPeerRequestByRandomID, randomID)
	var i GetPeerRequestByRandomIDRow
	err := row.Scan(
		&i.PeerRequest.ID,
		&i.PeerRequest.RandomID,
		&i.PeerRequest.InterfaceName,
		&i.PeerRequest.RequestedAt,
		&i.PeerRequest.RequestedByUserUuid,
		&i.PeerRequest.NodeID,
		&i.PeerRequest.OwnedByUserID,
		&i.PeerRequest.Status,
		&i.User.ID,
		&i.User.Uuid,
		&i.User.Name,
		&i.User.Scopes,
		&i.User.Fee,
		&i.User.PaidUntil,
		&i.User.IsBanned,
		&i.User.LoginTokenVersion,
		&i.User.RefreshTokenVersion,
		&i.Node.ID,
		&i.Node.Uuid,
		&i.Node.Name,
		&i.Node.BaseUrl,
		&i.Node.TlsClientKey,
		&i.Node.TlsClientCert,
		&i.Node.TlsServerCert,
		&i.Node.AllowedIps,
	)
	return i, err
}

const getPeerRequests = `-- name: GetPeerRequests :many
SELECT peer_requests.id, peer_requests.random_id, peer_requests.interface_name, peer_requests.requested_at, peer_requests.requested_by_user_uuid, peer_requests.node_id, peer_requests.owned_by_user_id, peer_requests.status, owners.id, owners.uuid, owners.name, owners.scopes, owners.fee, owners.paid_until, owners.is_banned, owners.login_token_version, owners.refresh_token_version, nodes.id, nodes.uuid, nodes.name, nodes.base_url, nodes.tls_client_key, nodes.tls_client_cert, nodes.tls_server_cert, nodes.allowed_ips
FROM peer_requests
    JOIN nodes on nodes.id = peer_requests.node_id
    JOIN users AS owners on owners.id = peer_requests.owned_by_user_id
ORDER BY requested_at DESC
`

type GetPeerRequestsRow struct {
	PeerRequest PeerRequest
	User        User
	Node        Node
}

func (q *Queries) GetPeerRequests(ctx context.Context) ([]GetPeerRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPeerRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPeerRequestsRow
	for rows.Next() {
		var i GetPeerRequestsRow
		if err := rows.Scan(
			&i.PeerRequest.ID,
			&i.PeerRequest.RandomID,
			&i.PeerRequest.InterfaceName,
			&i.PeerRequest.RequestedAt,
			&i.PeerRequest.RequestedByUserUuid,
			&i.PeerRequest.NodeID,
			&i.PeerRequest.OwnedByUserID,
			&i.PeerRequest.Status,
			&i.User.ID,
			&i.User.Uuid,
			&i.User.Name,
			&i.User.Scopes,
			&i.User.Fee,
			&i.User.PaidUntil,
			&i.User.IsBanned,
			&i.User.LoginTokenVersion,
			&i.User.RefreshTokenVersion,
			&i.Node.ID,
			&i.Node.Uuid,
			&i.Node.Name,
			&i.Node.BaseUrl,
			&i.Node.TlsClientKey,
			&i.Node.TlsClientCert,
			&i.Node.TlsServerCert,
			&i.Node.AllowedIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRequestEncryptionKeys = `-- name: GetRequestEncryptionKeys :one

SELECT key0, key1, rotate_after FROM request_encryption_keys LIMIT 1
`

// - ======= Request encryption keys =======
func (q *Queries) GetRequestEncryptionKeys(ctx context.Context) (RequestEncryptionKey, error) {
	row := q.db.QueryRowContext(ctx, getRequestEncryptionKeys)
	var i RequestEncryptionKey
	err := row.Scan(&i.Key0, &i.Key1, &i.RotateAfter)
	return i, err
}

const getUncompletedPeerRequestsForUser = `-- name: GetUncompletedPeerRequestsForUser :many
SELECT peer_requests.id, peer_requests.random_id, peer_requests.interface_name, peer_requests.requested_at, peer_requests.requested_by_user_uuid, peer_requests.node_id, peer_requests.owned_by_user_id, peer_requests.status, owners.id, owners.uuid, owners.name, owners.scopes, owners.fee, owners.paid_until, owners.is_banned, owners.login_token_version, owners.refresh_token_version, nodes.id, nodes.uuid, nodes.name, nodes.base_url, nodes.tls_client_key, nodes.tls_client_cert, nodes.tls_server_cert, nodes.allowed_ips
FROM peer_requests
    JOIN nodes on nodes.id = peer_requests.node_id
    JOIN users AS owners on owners.id = peer_requests.owned_by_user_id
WHERE
    owners.uuid = ?1 AND
    status NOT IN ('created', 'failed', 'cancelled')
ORDER BY requested_at DESC
`

type GetUncompletedPeerRequestsForUserRow struct {
	PeerRequest PeerRequest
	User        User
	Node        Node
}

func (q *Queries) GetUncompletedPeerRequestsForUser(ctx context.Context, userUuid string) ([]GetUncompletedPeerRequestsForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, getUncompletedPeerRequestsForUser, userUuid)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUncompletedPeerRequestsForUserRow
	for rows.Next() {
		var i GetUncompletedPeerRequestsForUserRow
		if err := rows.Scan(
			&i.PeerRequest.ID,
			&i.PeerRequest.RandomID,
			&i.PeerRequest.InterfaceName,
			&i.PeerRequest.RequestedAt,
			&i.PeerRequest.RequestedByUserUuid,
			&i.PeerRequest.NodeID,
			&i.PeerRequest.OwnedByUserID,
			&i.PeerRequest.Status,
			&i.User.ID,
			&i.User.Uuid,
			&i.User.Name,
			&i.User.Scopes,
			&i.User.Fee,
			&i.User.PaidUntil,
			&i.User.IsBanned,
			&i.User.LoginTokenVersion,
			&i.User.RefreshTokenVersion,
			&i.Node.ID,
			&i.Node.Uuid,
			&i.Node.Name,
			&i.Node.BaseUrl,
			&i.Node.TlsClientKey,
			&i.Node.TlsClientCert,
			&i.Node.TlsServerCert,
			&i.Node.AllowedIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAndUpdateForLogin = `-- name: GetUserAndUpdateForLogin :one
UPDATE users SET
    login_token_version = login_token_version +1
WHERE
    uuid = ?1
    AND login_token_version = ?2
RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type GetUserAndUpdateForLoginParams struct {
	Uuid                string
	CurrentLoginVersion int64
}

func (q *Queries) GetUserAndUpdateForLogin(ctx context.Context, arg GetUserAndUpdateForLoginParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserAndUpdateForLogin, arg.Uuid, arg.CurrentLoginVersion)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const getUserByName = `-- name: GetUserByName :one
SELECT id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version FROM users
WHERE name = ?1
`

func (q *Queries) GetUserByName(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByName, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const getUserByUUID = `-- name: GetUserByUUID :one
SELECT id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version FROM users
WHERE uuid = ?1
`

func (q *Queries) GetUserByUUID(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByUUID, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version FROM users
`

func (q *Queries) GetUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Uuid,
			&i.Name,
			&i.Scopes,
			&i.Fee,
			&i.PaidUntil,
			&i.IsBanned,
			&i.LoginTokenVersion,
			&i.RefreshTokenVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementUserLoginVersion = `-- name: IncrementUserLoginVersion :one
UPDATE users SET
    login_token_version = login_token_version + 1
WHERE
    uuid = ?1
RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

func (q *Queries) IncrementUserLoginVersion(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, incrementUserLoginVersion, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const incrementUserRefreshVersion = `-- name: IncrementUserRefreshVersion :one
UPDATE users SET
    refresh_token_version = refresh_token_version + 1
WHERE
    uuid = ?1
RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

func (q *Queries) IncrementUserRefreshVersion(ctx context.Context, uuid string) (User, error) {
	row := q.db.QueryRowContext(ctx, incrementUserRefreshVersion, uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const removeNode = `-- name: RemoveNode :execrows
DELETE FROM nodes WHERE id = ?1
`

func (q *Queries) RemoveNode(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeNode, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateNode = `-- name: UpdateNode :one
UPDATE nodes SET
    name = ?1,
    base_url = ?2,
    tls_client_key = ?3,
    tls_client_cert = ?4,
    tls_server_cert = ?5,
    allowed_ips = ?6
WHERE uuid = ?7
RETURNING id, uuid, name, base_url, tls_client_key, tls_client_cert, tls_server_cert, allowed_ips
`

type UpdateNodeParams struct {
	Name          string
	BaseUrl       string
	TlsClientKey  string
	TlsClientCert string
	TlsServerCert string
	AllowedIps    string
	Uuid          string
}

func (q *Queries) UpdateNode(ctx context.Context, arg UpdateNodeParams) (Node, error) {
	row := q.db.QueryRowContext(ctx, updateNode,
		arg.Name,
		arg.BaseUrl,
		arg.TlsClientKey,
		arg.TlsClientCert,
		arg.TlsServerCert,
		arg.AllowedIps,
		arg.Uuid,
	)
	var i Node
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.BaseUrl,
		&i.TlsClientKey,
		&i.TlsClientCert,
		&i.TlsServerCert,
		&i.AllowedIps,
	)
	return i, err
}

const updatePeerRequest = `-- name: UpdatePeerRequest :execrows
UPDATE peer_requests SET
    interface_name = ?1,
    requested_at = ?2,
    requested_by_user_uuid = ?3,
    status = ?4
WHERE
    random_id = ?5
`

type UpdatePeerRequestParams struct {
	InterfaceName       string
	RequestedAt         time.Time
	RequestedByUserUuid *string
	Status              string
	RandomID            string
}

func (q *Queries) UpdatePeerRequest(ctx context.Context, arg UpdatePeerRequestParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updatePeerRequest,
		arg.InterfaceName,
		arg.RequestedAt,
		arg.RequestedByUserUuid,
		arg.Status,
		arg.RandomID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateRequestEncryptionKeys = `-- name: UpdateRequestEncryptionKeys :execrows
UPDATE request_encryption_keys SET
    key0 = ?1,
    key1 = ?2,
    rotate_after = ?3
`

type UpdateRequestEncryptionKeysParams struct {
	Key0        *string
	Key1        *string
	RotateAfter time.Time
}

func (q *Queries) UpdateRequestEncryptionKeys(ctx context.Context, arg UpdateRequestEncryptionKeysParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateRequestEncryptionKeys, arg.Key0, arg.Key1, arg.RotateAfter)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    name = ?1,
    scopes = ?2,
    fee = ?3
WHERE uuid = ?4
RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type UpdateUserParams struct {
	Name   string
	Scopes string
	Fee    string
	Uuid   string
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUser,
		arg.Name,
		arg.Scopes,
		arg.Fee,
		arg.Uuid,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}

const updateUserPaidUntil = `-- name: UpdateUserPaidUntil :one
UPDATE users SET
    paid_until = ?1
WHERE uuid = ?2
RETURNING id, uuid, name, scopes, fee, paid_until, is_banned, login_token_version, refresh_token_version
`

type UpdateUserPaidUntilParams struct {
	PaidUntil *time.Time
	Uuid      string
}

func (q *Queries) UpdateUserPaidUntil(ctx context.Context, arg UpdateUserPaidUntilParams) (User, error) {
	row := q.db.QueryRowContext(ctx, updateUserPaidUntil, arg.PaidUntil, arg.Uuid)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Uuid,
		&i.Name,
		&i.Scopes,
		&i.Fee,
		&i.PaidUntil,
		&i.IsBanned,
		&i.LoginTokenVersion,
		&i.RefreshTokenVersion,
	)
	return i, err
}
